
groups:
  - name: system_alerts
    rules:
      - alert: HighCPUUsage
        expr: avg(rate(node_cpu_seconds_total{mode!="idle"}[1m])) > 0.8
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Cảnh báo CPU cao"
          description: "CPU sử dụng vượt ngưỡng 80% trong 2 phút."
